version: '3.7'
networks:
  shared-network:
    driver: bridge

services:
  zakroma_db:
    container_name: zakroma_db
    networks:
      - shared-network
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./database/scripts/:/docker-entrypoint-initdb.d # initdb scripts

  zakroma_backend:
    image: zakroma_backend:latest
    container_name: zakroma_backend
    networks:
      - shared-network
    build:
      dockerfile: Dockerfile
      context: .
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - zakroma_db
